# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Pure65"
product_name = "Pure65"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "FoxTimo"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
input_pins = ["P1_00", "P0_24", "P0_22", "P1_07", "P1_02"] # rows
output_pins = ["P0_11", "P1_04", "P1_06", "P0_09", "P0_10", "P0_11", "P0_13", "P0_15", "P0_02", "P0_29", "P0_31", "P0_06", "P0_08", "P0_17", "P0_20"] # columns
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 5
cols = 15
layers = 2
keymap = [
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus", "Equal", "Backspace", "Insert"],
        ["Tab", "Q", "W", "E", "R", "T", "Z", "U", "I", "O", "P", "LeftBracket", "RightBracket", "_", "Delete"],
        ["CapsLock", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote", "NonusBackslash", "Enter", "PageUp"],
        ["LShift", "NonusBackslash", "Y", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash", "Rshift", "Up", "PageDown"],
        ["LCTRL", "LGUI", "LALT", "_", "_", "SPACE", "_", "_", "_", "RAlt", "MO(1)", "RCtrl", "Left", "Down", "Right"]
    ],
    [
        ["Grave", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12", "_" , "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "MediaPlayPause", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "AudioMute", "_", "_", "_", "_", "VolumeUp", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "MediaPrevTrack", "VolumeDown", "MediaNextTrack"]
    ]
    
]

[ble]
enabled = true
battery_adc_pin = "vddh"

[storage]
# Storage feature is enabled by default
enabled = true
# Start address of local storage, MUST BE start of a sector.
# If start_addr is set to 0(this is the default value), the last `num_sectors` sectors will be used.
start_addr = 0x00000000
# How many sectors are used for storage, the default value is 2
num_sectors = 2
